global:
  env: testing
# enable sig-provider deploy
sigProvider:
  enabled: true
  image:
    _default: ghcr.io/blockscout/sig-provider:main

  replicas:
    app: 1
  docker:
    port: 80
    targetPort: 8043
    metricsPort: 6060

  # enable ingress
  ingress:
    enabled: true
    annotations: {}
    host:
      _default: sig-provider-test.aws-k8s.blockscout.com
    # enable https
    tls:
      enabled: true

  resources:
    limits:
      memory:
        _default: "0.05Gi"
      cpu:
        _default: "0.05"
    requests:
      memory:
        _default: "0.05Gi"
      cpu:
        _default: "0.05"

  environment:
    SIG_PROVIDER__METRICS__ENABLED:
      _default: 'true'
    SIG_PROVIDER__SERVER__HTTP__ADDR:
      _default: 0.0.0.0:8043
    SIG_PROVIDER__SERVER__GRPC__ENABLED:
      _default: 'false'
    # ENV:
    #   _default: 'true'
